### ISSUE TITLE
syntax error : expected ':' or '=' separaror

### ISSUE THREAD

**Issue by krunal1313** [chunying/gaminganywhere#10]
When I compile by runnnng command 'nmake /f NMakefile all' it gives the following error in file 'ga/server/periodic/NMakefile'

fatal error U1035 : syntax error : expected ':' or '=' separator
stop.

I re-downloaded source many times and tried but same error existing.

**Comment by dadouf** [comment]
What is your OS?

**Comment by chunying** [comment]
This is because your git client may be not properly handle symbolic links in Windows. You may download the zip file from our website http://gaminganywhere.org. Alternatively, you can install CYGWIN (with git and zip util installed), and then in CYGWIN bash:
1) clone source codes using git clone command. CYGWIN supports symbolic links, so the links work well
2) use zip to compress the cloned gaminganywhere directory, e.g., 'zip -ur ga.zip gaminganywhere'
3) unzip the gz.zip file generated in step 2. all the symbolic links should be resolved properly.
