### ISSUE TITLE
Build for Steam OS

### ISSUE THREAD

**Issue by moocow1452** [chunying/gaminganywhere#3]
Could something like this either backpack or replace inhome streaming, install on top of Steam OS and stream games elsewhere?

**Comment by Ghostbird** [comment]
It depends on what you qualify as Steam OS. I haven't seen a read Steam OS release yet. However if you want just the functionality of Steam OS. You can just install Debian and install Steam on Debian. I am currently compiling this software on Debian and Raspbian (Raspberry Pi) because Steam Streaming cannot be used with the Raspberry Pi. (Because Steam is only available for x86 CPUs and OpenGL GPUs and the Raspberry Pi 1 and 2 use ARM CPUs and OpenGL ES GPUs.)
I hope this will allow me to stream my games from my main system to the Raspberry Pi. However whether it works remains to be seen.

So YES, this _may_ replace Steam in-home streaming. However, you _may_ even be able to install it on SteamOS, however I suggest grabbing a more mature Linux distribution and installing Steam on that. Your best bet is probably Ubuntu, since it is newbie friendly, and Steam for Linux currently is "officially" supported on Ubuntu.

However from the fact that you did not know the answer to this question, I am guessing that you are rather new to all the Linux and Open Source stuff. In that case (and I may be wrong), I would like to remind you that it WILL take quite some work and study to get this software to work, and when it works it may not yet work well with the particular games you try to run.
